# Generated by Django 5.2.7 on 2025-10-02 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0001_initial'),
        ('clientes', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(db_index=True, max_length=20)),
                ('tipo_interacao', models.CharField(db_index=True, max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalhes', models.JSONField(default=dict)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_contato', to='chatbots.chatbot')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Métrica de Contato',
                'verbose_name_plural': 'Métricas de Contato',
                'db_table': 'metricas_contato',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['chatbot', 'data_hora'], name='metricas_co_chatbot_03ee19_idx'), models.Index(fields=['tipo_interacao', 'data_hora'], name='metricas_co_tipo_in_edeb41_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalhes', models.JSONField(default=dict)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_pedido', to='chatbots.chatbot')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Métrica de Pedido',
                'verbose_name_plural': 'Métricas de Pedido',
                'db_table': 'metricas_pedido',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['chatbot', 'data_hora'], name='metricas_pe_chatbot_7d9461_idx'), models.Index(fields=['status', 'data_hora'], name='metricas_pe_status_c75b19_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricaReativacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(max_length=20)),
                ('mensagem_enviada', models.TextField()),
                ('sucesso', models.BooleanField(db_index=True, default=False)),
                ('resposta_cliente', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalhes', models.JSONField(default=dict)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_reativacao', to='chatbots.chatbot')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Métrica de Reativação',
                'verbose_name_plural': 'Métricas de Reativação',
                'db_table': 'metricas_reativacao',
                'ordering': ['-data_envio'],
                'indexes': [models.Index(fields=['chatbot', 'data_envio'], name='metricas_re_chatbot_e7d2b5_idx'), models.Index(fields=['sucesso', 'data_envio'], name='metricas_re_sucesso_9f5ab2_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_venda', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detalhes', models.JSONField(default=dict)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_venda', to='chatbots.chatbot')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Métrica de Venda',
                'verbose_name_plural': 'Métricas de Venda',
                'db_table': 'metricas_venda',
                'ordering': ['-data_venda'],
                'indexes': [models.Index(fields=['chatbot', 'data_venda'], name='metricas_ve_chatbot_19ef1a_idx')],
            },
        ),
    ]
