# Generated by Django 5.2.7 on 2025-10-02 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('numero_telefone', models.CharField(max_length=20, unique=True)),
                ('meta_phone_number_id', models.CharField(max_length=100, unique=True)),
                ('meta_business_account_id', models.CharField(max_length=100)),
                ('meta_access_token', models.CharField(max_length=500)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'db_table': 'chatbots',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('handler_path', models.CharField(max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='chatbots.chatbot')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'etapas',
                'ordering': ['chatbot', 'ordem'],
                'unique_together': {('chatbot', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(db_index=True, max_length=20)),
                ('contexto', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='ativo', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='clientes.cliente')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='chatbots.chatbot')),
                ('etapa_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chatbots.etapa')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'db_table': 'atendimentos',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('direcao', models.CharField(choices=[('recebida', 'Recebida'), ('enviada', 'Enviada')], db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('interactive', 'Interativo'), ('image', 'Imagem'), ('audio', 'Áudio'), ('document', 'Documento'), ('video', 'Vídeo'), ('location', 'Localização'), ('contacts', 'Contatos'), ('sticker', 'Sticker'), ('button', 'Botão'), ('unknown', 'Desconhecido')], default='text', max_length=20)),
                ('conteudo', models.TextField()),
                ('payload_completo', models.JSONField(default=dict)),
                ('processada', models.BooleanField(db_index=True, default=False)),
                ('enviada_com_sucesso', models.BooleanField(db_index=True, default=False)),
                ('erro', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chatbots.atendimento')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'mensagens',
                'ordering': ['criada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['chatbot', 'numero_whatsapp', 'status'], name='atendimento_chatbot_d6364d_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['atendimento', 'criada_em'], name='mensagens_atendim_ae2e32_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['processada', 'criada_em'], name='mensagens_process_2978a9_idx'),
        ),
    ]
