# Generated by Django 5.2.7 on 2025-10-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='meta_app_secret',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='verify_token',
            field=models.CharField(default='initial_token', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
