# Generated by Django 5.2.7 on 2025-10-02 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('api_externa', 'API Externa'), ('banco_direto', 'Acesso Direto ao Banco'), ('webhook', 'Webhook'), ('outro', 'Outro')], db_index=True, max_length=20)),
                ('url_base', models.URLField(blank=True)),
                ('credenciais', models.JSONField(default=dict)),
                ('headers_padrao', models.JSONField(default=dict)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('configuracoes_extras', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Integração',
                'verbose_name_plural': 'Configurações de Integração',
                'db_table': 'configuracoes_integracao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LogIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=20)),
                ('endpoint', models.CharField(max_length=500)),
                ('payload_enviado', models.JSONField(default=dict)),
                ('resposta_recebida', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(null=True)),
                ('sucesso', models.BooleanField(db_index=True, default=False)),
                ('erro', models.TextField(blank=True)),
                ('tempo_resposta_ms', models.IntegerField(null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integracoes.configuracaointegracao')),
            ],
            options={
                'verbose_name': 'Log de Integração',
                'verbose_name_plural': 'Logs de Integração',
                'db_table': 'logs_integracao',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['configuracao', 'criado_em'], name='logs_integr_configu_be24d5_idx'), models.Index(fields=['sucesso', 'criado_em'], name='logs_integr_sucesso_d17a52_idx')],
            },
        ),
    ]
